// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_db_account.proto

#include "game_db_account.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_game_5fdb_5faccount_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_game_5fdb_5faccount_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_RoleInfo;
}  // namespace protobuf_game_5fdb_5faccount_2eproto
namespace DBAccount {
class DBUserAccountDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DBUserAccount>
      _instance;
} _DBUserAccount_default_instance_;
class RoleInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RoleInfo>
      _instance;
} _RoleInfo_default_instance_;
class DBRoleInfoListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DBRoleInfoList>
      _instance;
} _DBRoleInfoList_default_instance_;
}  // namespace DBAccount
namespace protobuf_game_5fdb_5faccount_2eproto {
static void InitDefaultsDBUserAccount() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DBAccount::_DBUserAccount_default_instance_;
    new (ptr) ::DBAccount::DBUserAccount();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DBAccount::DBUserAccount::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DBUserAccount =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDBUserAccount}, {}};

static void InitDefaultsRoleInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DBAccount::_RoleInfo_default_instance_;
    new (ptr) ::DBAccount::RoleInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DBAccount::RoleInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RoleInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRoleInfo}, {}};

static void InitDefaultsDBRoleInfoList() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DBAccount::_DBRoleInfoList_default_instance_;
    new (ptr) ::DBAccount::DBRoleInfoList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DBAccount::DBRoleInfoList::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_DBRoleInfoList =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsDBRoleInfoList}, {
      &protobuf_game_5fdb_5faccount_2eproto::scc_info_RoleInfo.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_DBUserAccount.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RoleInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DBRoleInfoList.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, account_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, password_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, password_hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, session_key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, v_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, s_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, register_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, last_ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, last_login_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, os_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, is_banned_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBUserAccount, tokon_key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::RoleInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::RoleInfo, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::RoleInfo, server_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::RoleInfo, role_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBRoleInfoList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DBAccount::DBRoleInfoList, role_list_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::DBAccount::DBUserAccount)},
  { 18, -1, sizeof(::DBAccount::RoleInfo)},
  { 26, -1, sizeof(::DBAccount::DBRoleInfoList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::DBAccount::_DBUserAccount_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DBAccount::_RoleInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DBAccount::_DBRoleInfoList_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "game_db_account.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025game_db_account.proto\022\tDBAccount\"\375\001\n\rD"
      "BUserAccount\022\017\n\007user_id\030\001 \001(\t\022\024\n\014account"
      "_name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\025\n\rpasswor"
      "d_hash\030\004 \001(\t\022\023\n\013session_key\030\005 \001(\t\022\t\n\001v\030\006"
      " \001(\t\022\t\n\001s\030\007 \001(\t\022\025\n\rregister_time\030\010 \001(\t\022\017"
      "\n\007last_ip\030\t \001(\t\022\027\n\017last_login_time\030\n \001(\t"
      "\022\n\n\002os\030\013 \001(\t\022\021\n\tis_banned\030\014 \001(\010\022\021\n\ttokon"
      "_key\030\r \001(\t\"E\n\010RoleInfo\022\021\n\tserver_id\030\001 \001("
      "\005\022\023\n\013server_name\030\002 \001(\t\022\021\n\trole_name\030\003 \001("
      "\t\"8\n\016DBRoleInfoList\022&\n\trole_list\030\001 \003(\0132\023"
      ".DBAccount.RoleInfob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 427);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "game_db_account.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_game_5fdb_5faccount_2eproto
namespace DBAccount {

// ===================================================================

void DBUserAccount::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DBUserAccount::kUserIdFieldNumber;
const int DBUserAccount::kAccountNameFieldNumber;
const int DBUserAccount::kPasswordFieldNumber;
const int DBUserAccount::kPasswordHashFieldNumber;
const int DBUserAccount::kSessionKeyFieldNumber;
const int DBUserAccount::kVFieldNumber;
const int DBUserAccount::kSFieldNumber;
const int DBUserAccount::kRegisterTimeFieldNumber;
const int DBUserAccount::kLastIpFieldNumber;
const int DBUserAccount::kLastLoginTimeFieldNumber;
const int DBUserAccount::kOsFieldNumber;
const int DBUserAccount::kIsBannedFieldNumber;
const int DBUserAccount::kTokonKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DBUserAccount::DBUserAccount()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fdb_5faccount_2eproto::scc_info_DBUserAccount.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DBAccount.DBUserAccount)
}
DBUserAccount::DBUserAccount(const DBUserAccount& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user_id().size() > 0) {
    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  account_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.account_name().size() > 0) {
    account_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_name_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  password_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password_hash().size() > 0) {
    password_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_hash_);
  }
  session_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.session_key().size() > 0) {
    session_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.session_key_);
  }
  v_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.v().size() > 0) {
    v_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.v_);
  }
  s_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.s().size() > 0) {
    s_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.s_);
  }
  register_time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.register_time().size() > 0) {
    register_time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.register_time_);
  }
  last_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.last_ip().size() > 0) {
    last_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_ip_);
  }
  last_login_time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.last_login_time().size() > 0) {
    last_login_time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_login_time_);
  }
  os_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.os().size() > 0) {
    os_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.os_);
  }
  tokon_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tokon_key().size() > 0) {
    tokon_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tokon_key_);
  }
  is_banned_ = from.is_banned_;
  // @@protoc_insertion_point(copy_constructor:DBAccount.DBUserAccount)
}

void DBUserAccount::SharedCtor() {
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  v_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  s_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  register_time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_login_time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tokon_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_banned_ = false;
}

DBUserAccount::~DBUserAccount() {
  // @@protoc_insertion_point(destructor:DBAccount.DBUserAccount)
  SharedDtor();
}

void DBUserAccount::SharedDtor() {
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  v_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  s_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  register_time_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_login_time_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tokon_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DBUserAccount::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DBUserAccount::descriptor() {
  ::protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DBUserAccount& DBUserAccount::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fdb_5faccount_2eproto::scc_info_DBUserAccount.base);
  return *internal_default_instance();
}


void DBUserAccount::Clear() {
// @@protoc_insertion_point(message_clear_start:DBAccount.DBUserAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  v_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  s_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  register_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_login_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tokon_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_banned_ = false;
  _internal_metadata_.Clear();
}

bool DBUserAccount::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DBAccount.DBUserAccount)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->user_id().data(), static_cast<int>(this->user_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.user_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string account_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account_name().data(), static_cast<int>(this->account_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.account_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password_hash = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password_hash()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password_hash().data(), static_cast<int>(this->password_hash().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.password_hash"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string session_key = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->session_key().data(), static_cast<int>(this->session_key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.session_key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string v = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_v()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->v().data(), static_cast<int>(this->v().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.v"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string s = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_s()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->s().data(), static_cast<int>(this->s().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.s"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string register_time = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_register_time()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->register_time().data(), static_cast<int>(this->register_time().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.register_time"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string last_ip = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_last_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->last_ip().data(), static_cast<int>(this->last_ip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.last_ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string last_login_time = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_last_login_time()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->last_login_time().data(), static_cast<int>(this->last_login_time().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.last_login_time"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string os = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_os()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->os().data(), static_cast<int>(this->os().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.os"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_banned = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_banned_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string tokon_key = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tokon_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tokon_key().data(), static_cast<int>(this->tokon_key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.DBUserAccount.tokon_key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DBAccount.DBUserAccount)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DBAccount.DBUserAccount)
  return false;
#undef DO_
}

void DBUserAccount::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DBAccount.DBUserAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user_id = 1;
  if (this->user_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user_id().data(), static_cast<int>(this->user_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.user_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->user_id(), output);
  }

  // string account_name = 2;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), static_cast<int>(this->account_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.account_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->account_name(), output);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->password(), output);
  }

  // string password_hash = 4;
  if (this->password_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password_hash().data(), static_cast<int>(this->password_hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.password_hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->password_hash(), output);
  }

  // string session_key = 5;
  if (this->session_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_key().data(), static_cast<int>(this->session_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.session_key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->session_key(), output);
  }

  // string v = 6;
  if (this->v().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->v().data(), static_cast<int>(this->v().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.v");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->v(), output);
  }

  // string s = 7;
  if (this->s().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->s().data(), static_cast<int>(this->s().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.s");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->s(), output);
  }

  // string register_time = 8;
  if (this->register_time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->register_time().data(), static_cast<int>(this->register_time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.register_time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->register_time(), output);
  }

  // string last_ip = 9;
  if (this->last_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->last_ip().data(), static_cast<int>(this->last_ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.last_ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->last_ip(), output);
  }

  // string last_login_time = 10;
  if (this->last_login_time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->last_login_time().data(), static_cast<int>(this->last_login_time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.last_login_time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->last_login_time(), output);
  }

  // string os = 11;
  if (this->os().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->os().data(), static_cast<int>(this->os().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.os");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->os(), output);
  }

  // bool is_banned = 12;
  if (this->is_banned() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->is_banned(), output);
  }

  // string tokon_key = 13;
  if (this->tokon_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tokon_key().data(), static_cast<int>(this->tokon_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.tokon_key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->tokon_key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DBAccount.DBUserAccount)
}

::google::protobuf::uint8* DBUserAccount::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DBAccount.DBUserAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user_id = 1;
  if (this->user_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user_id().data(), static_cast<int>(this->user_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.user_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->user_id(), target);
  }

  // string account_name = 2;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), static_cast<int>(this->account_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.account_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->account_name(), target);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }

  // string password_hash = 4;
  if (this->password_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password_hash().data(), static_cast<int>(this->password_hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.password_hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->password_hash(), target);
  }

  // string session_key = 5;
  if (this->session_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_key().data(), static_cast<int>(this->session_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.session_key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->session_key(), target);
  }

  // string v = 6;
  if (this->v().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->v().data(), static_cast<int>(this->v().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.v");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->v(), target);
  }

  // string s = 7;
  if (this->s().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->s().data(), static_cast<int>(this->s().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.s");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->s(), target);
  }

  // string register_time = 8;
  if (this->register_time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->register_time().data(), static_cast<int>(this->register_time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.register_time");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->register_time(), target);
  }

  // string last_ip = 9;
  if (this->last_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->last_ip().data(), static_cast<int>(this->last_ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.last_ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->last_ip(), target);
  }

  // string last_login_time = 10;
  if (this->last_login_time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->last_login_time().data(), static_cast<int>(this->last_login_time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.last_login_time");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->last_login_time(), target);
  }

  // string os = 11;
  if (this->os().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->os().data(), static_cast<int>(this->os().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.os");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->os(), target);
  }

  // bool is_banned = 12;
  if (this->is_banned() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->is_banned(), target);
  }

  // string tokon_key = 13;
  if (this->tokon_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tokon_key().data(), static_cast<int>(this->tokon_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.DBUserAccount.tokon_key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->tokon_key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBAccount.DBUserAccount)
  return target;
}

size_t DBUserAccount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBAccount.DBUserAccount)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string user_id = 1;
  if (this->user_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->user_id());
  }

  // string account_name = 2;
  if (this->account_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account_name());
  }

  // string password = 3;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // string password_hash = 4;
  if (this->password_hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password_hash());
  }

  // string session_key = 5;
  if (this->session_key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->session_key());
  }

  // string v = 6;
  if (this->v().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->v());
  }

  // string s = 7;
  if (this->s().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->s());
  }

  // string register_time = 8;
  if (this->register_time().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->register_time());
  }

  // string last_ip = 9;
  if (this->last_ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->last_ip());
  }

  // string last_login_time = 10;
  if (this->last_login_time().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->last_login_time());
  }

  // string os = 11;
  if (this->os().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->os());
  }

  // string tokon_key = 13;
  if (this->tokon_key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->tokon_key());
  }

  // bool is_banned = 12;
  if (this->is_banned() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DBUserAccount::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DBAccount.DBUserAccount)
  GOOGLE_DCHECK_NE(&from, this);
  const DBUserAccount* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DBUserAccount>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DBAccount.DBUserAccount)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DBAccount.DBUserAccount)
    MergeFrom(*source);
  }
}

void DBUserAccount::MergeFrom(const DBUserAccount& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DBAccount.DBUserAccount)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.user_id().size() > 0) {

    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  if (from.account_name().size() > 0) {

    account_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_name_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.password_hash().size() > 0) {

    password_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_hash_);
  }
  if (from.session_key().size() > 0) {

    session_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.session_key_);
  }
  if (from.v().size() > 0) {

    v_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.v_);
  }
  if (from.s().size() > 0) {

    s_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.s_);
  }
  if (from.register_time().size() > 0) {

    register_time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.register_time_);
  }
  if (from.last_ip().size() > 0) {

    last_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_ip_);
  }
  if (from.last_login_time().size() > 0) {

    last_login_time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_login_time_);
  }
  if (from.os().size() > 0) {

    os_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.os_);
  }
  if (from.tokon_key().size() > 0) {

    tokon_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tokon_key_);
  }
  if (from.is_banned() != 0) {
    set_is_banned(from.is_banned());
  }
}

void DBUserAccount::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DBAccount.DBUserAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DBUserAccount::CopyFrom(const DBUserAccount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBAccount.DBUserAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DBUserAccount::IsInitialized() const {
  return true;
}

void DBUserAccount::Swap(DBUserAccount* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DBUserAccount::InternalSwap(DBUserAccount* other) {
  using std::swap;
  user_id_.Swap(&other->user_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  account_name_.Swap(&other->account_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_hash_.Swap(&other->password_hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  session_key_.Swap(&other->session_key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  v_.Swap(&other->v_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  s_.Swap(&other->s_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  register_time_.Swap(&other->register_time_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  last_ip_.Swap(&other->last_ip_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  last_login_time_.Swap(&other->last_login_time_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  os_.Swap(&other->os_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  tokon_key_.Swap(&other->tokon_key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(is_banned_, other->is_banned_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DBUserAccount::GetMetadata() const {
  protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RoleInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RoleInfo::kServerIdFieldNumber;
const int RoleInfo::kServerNameFieldNumber;
const int RoleInfo::kRoleNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RoleInfo::RoleInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fdb_5faccount_2eproto::scc_info_RoleInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DBAccount.RoleInfo)
}
RoleInfo::RoleInfo(const RoleInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  server_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.server_name().size() > 0) {
    server_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.server_name_);
  }
  role_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.role_name().size() > 0) {
    role_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.role_name_);
  }
  server_id_ = from.server_id_;
  // @@protoc_insertion_point(copy_constructor:DBAccount.RoleInfo)
}

void RoleInfo::SharedCtor() {
  server_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  role_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  server_id_ = 0;
}

RoleInfo::~RoleInfo() {
  // @@protoc_insertion_point(destructor:DBAccount.RoleInfo)
  SharedDtor();
}

void RoleInfo::SharedDtor() {
  server_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  role_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RoleInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RoleInfo::descriptor() {
  ::protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RoleInfo& RoleInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fdb_5faccount_2eproto::scc_info_RoleInfo.base);
  return *internal_default_instance();
}


void RoleInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:DBAccount.RoleInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  server_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  role_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  server_id_ = 0;
  _internal_metadata_.Clear();
}

bool RoleInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DBAccount.RoleInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 server_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &server_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string server_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_server_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->server_name().data(), static_cast<int>(this->server_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.RoleInfo.server_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string role_name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_role_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->role_name().data(), static_cast<int>(this->role_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DBAccount.RoleInfo.role_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DBAccount.RoleInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DBAccount.RoleInfo)
  return false;
#undef DO_
}

void RoleInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DBAccount.RoleInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 server_id = 1;
  if (this->server_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->server_id(), output);
  }

  // string server_name = 2;
  if (this->server_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->server_name().data(), static_cast<int>(this->server_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.RoleInfo.server_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->server_name(), output);
  }

  // string role_name = 3;
  if (this->role_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->role_name().data(), static_cast<int>(this->role_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.RoleInfo.role_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->role_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DBAccount.RoleInfo)
}

::google::protobuf::uint8* RoleInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DBAccount.RoleInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 server_id = 1;
  if (this->server_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->server_id(), target);
  }

  // string server_name = 2;
  if (this->server_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->server_name().data(), static_cast<int>(this->server_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.RoleInfo.server_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->server_name(), target);
  }

  // string role_name = 3;
  if (this->role_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->role_name().data(), static_cast<int>(this->role_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DBAccount.RoleInfo.role_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->role_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBAccount.RoleInfo)
  return target;
}

size_t RoleInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBAccount.RoleInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string server_name = 2;
  if (this->server_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->server_name());
  }

  // string role_name = 3;
  if (this->role_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->role_name());
  }

  // int32 server_id = 1;
  if (this->server_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->server_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RoleInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DBAccount.RoleInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const RoleInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RoleInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DBAccount.RoleInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DBAccount.RoleInfo)
    MergeFrom(*source);
  }
}

void RoleInfo::MergeFrom(const RoleInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DBAccount.RoleInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.server_name().size() > 0) {

    server_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.server_name_);
  }
  if (from.role_name().size() > 0) {

    role_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.role_name_);
  }
  if (from.server_id() != 0) {
    set_server_id(from.server_id());
  }
}

void RoleInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DBAccount.RoleInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RoleInfo::CopyFrom(const RoleInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBAccount.RoleInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoleInfo::IsInitialized() const {
  return true;
}

void RoleInfo::Swap(RoleInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RoleInfo::InternalSwap(RoleInfo* other) {
  using std::swap;
  server_name_.Swap(&other->server_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  role_name_.Swap(&other->role_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(server_id_, other->server_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RoleInfo::GetMetadata() const {
  protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DBRoleInfoList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DBRoleInfoList::kRoleListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DBRoleInfoList::DBRoleInfoList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fdb_5faccount_2eproto::scc_info_DBRoleInfoList.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DBAccount.DBRoleInfoList)
}
DBRoleInfoList::DBRoleInfoList(const DBRoleInfoList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      role_list_(from.role_list_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DBAccount.DBRoleInfoList)
}

void DBRoleInfoList::SharedCtor() {
}

DBRoleInfoList::~DBRoleInfoList() {
  // @@protoc_insertion_point(destructor:DBAccount.DBRoleInfoList)
  SharedDtor();
}

void DBRoleInfoList::SharedDtor() {
}

void DBRoleInfoList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DBRoleInfoList::descriptor() {
  ::protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DBRoleInfoList& DBRoleInfoList::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fdb_5faccount_2eproto::scc_info_DBRoleInfoList.base);
  return *internal_default_instance();
}


void DBRoleInfoList::Clear() {
// @@protoc_insertion_point(message_clear_start:DBAccount.DBRoleInfoList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  role_list_.Clear();
  _internal_metadata_.Clear();
}

bool DBRoleInfoList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DBAccount.DBRoleInfoList)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .DBAccount.RoleInfo role_list = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_role_list()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DBAccount.DBRoleInfoList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DBAccount.DBRoleInfoList)
  return false;
#undef DO_
}

void DBRoleInfoList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DBAccount.DBRoleInfoList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .DBAccount.RoleInfo role_list = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->role_list_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->role_list(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DBAccount.DBRoleInfoList)
}

::google::protobuf::uint8* DBRoleInfoList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DBAccount.DBRoleInfoList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .DBAccount.RoleInfo role_list = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->role_list_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->role_list(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBAccount.DBRoleInfoList)
  return target;
}

size_t DBRoleInfoList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBAccount.DBRoleInfoList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .DBAccount.RoleInfo role_list = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->role_list_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->role_list(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DBRoleInfoList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DBAccount.DBRoleInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  const DBRoleInfoList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DBRoleInfoList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DBAccount.DBRoleInfoList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DBAccount.DBRoleInfoList)
    MergeFrom(*source);
  }
}

void DBRoleInfoList::MergeFrom(const DBRoleInfoList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DBAccount.DBRoleInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  role_list_.MergeFrom(from.role_list_);
}

void DBRoleInfoList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DBAccount.DBRoleInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DBRoleInfoList::CopyFrom(const DBRoleInfoList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBAccount.DBRoleInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DBRoleInfoList::IsInitialized() const {
  return true;
}

void DBRoleInfoList::Swap(DBRoleInfoList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DBRoleInfoList::InternalSwap(DBRoleInfoList* other) {
  using std::swap;
  CastToBase(&role_list_)->InternalSwap(CastToBase(&other->role_list_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DBRoleInfoList::GetMetadata() const {
  protobuf_game_5fdb_5faccount_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fdb_5faccount_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace DBAccount
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DBAccount::DBUserAccount* Arena::CreateMaybeMessage< ::DBAccount::DBUserAccount >(Arena* arena) {
  return Arena::CreateInternal< ::DBAccount::DBUserAccount >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DBAccount::RoleInfo* Arena::CreateMaybeMessage< ::DBAccount::RoleInfo >(Arena* arena) {
  return Arena::CreateInternal< ::DBAccount::RoleInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DBAccount::DBRoleInfoList* Arena::CreateMaybeMessage< ::DBAccount::DBRoleInfoList >(Arena* arena) {
  return Arena::CreateInternal< ::DBAccount::DBRoleInfoList >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
