// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_db_account.proto

#ifndef PROTOBUF_INCLUDED_game_5fdb_5faccount_2eproto
#define PROTOBUF_INCLUDED_game_5fdb_5faccount_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_game_5fdb_5faccount_2eproto 

namespace protobuf_game_5fdb_5faccount_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_game_5fdb_5faccount_2eproto
namespace DBAccount {
class UserAccount;
class UserAccountDefaultTypeInternal;
extern UserAccountDefaultTypeInternal _UserAccount_default_instance_;
}  // namespace DBAccount
namespace google {
namespace protobuf {
template<> ::DBAccount::UserAccount* Arena::CreateMaybeMessage<::DBAccount::UserAccount>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace DBAccount {

// ===================================================================

class UserAccount : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DBAccount.UserAccount) */ {
 public:
  UserAccount();
  virtual ~UserAccount();

  UserAccount(const UserAccount& from);

  inline UserAccount& operator=(const UserAccount& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserAccount(UserAccount&& from) noexcept
    : UserAccount() {
    *this = ::std::move(from);
  }

  inline UserAccount& operator=(UserAccount&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserAccount& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserAccount* internal_default_instance() {
    return reinterpret_cast<const UserAccount*>(
               &_UserAccount_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UserAccount* other);
  friend void swap(UserAccount& a, UserAccount& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserAccount* New() const final {
    return CreateMaybeMessage<UserAccount>(NULL);
  }

  UserAccount* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UserAccount>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UserAccount& from);
  void MergeFrom(const UserAccount& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserAccount* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  #if LANG_CXX11
  void set_user_id(::std::string&& value);
  #endif
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // string account_name = 2;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 2;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  #if LANG_CXX11
  void set_account_name(::std::string&& value);
  #endif
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string password_hash = 4;
  void clear_password_hash();
  static const int kPasswordHashFieldNumber = 4;
  const ::std::string& password_hash() const;
  void set_password_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_password_hash(::std::string&& value);
  #endif
  void set_password_hash(const char* value);
  void set_password_hash(const char* value, size_t size);
  ::std::string* mutable_password_hash();
  ::std::string* release_password_hash();
  void set_allocated_password_hash(::std::string* password_hash);

  // string session_key = 5;
  void clear_session_key();
  static const int kSessionKeyFieldNumber = 5;
  const ::std::string& session_key() const;
  void set_session_key(const ::std::string& value);
  #if LANG_CXX11
  void set_session_key(::std::string&& value);
  #endif
  void set_session_key(const char* value);
  void set_session_key(const char* value, size_t size);
  ::std::string* mutable_session_key();
  ::std::string* release_session_key();
  void set_allocated_session_key(::std::string* session_key);

  // string v = 6;
  void clear_v();
  static const int kVFieldNumber = 6;
  const ::std::string& v() const;
  void set_v(const ::std::string& value);
  #if LANG_CXX11
  void set_v(::std::string&& value);
  #endif
  void set_v(const char* value);
  void set_v(const char* value, size_t size);
  ::std::string* mutable_v();
  ::std::string* release_v();
  void set_allocated_v(::std::string* v);

  // string s = 7;
  void clear_s();
  static const int kSFieldNumber = 7;
  const ::std::string& s() const;
  void set_s(const ::std::string& value);
  #if LANG_CXX11
  void set_s(::std::string&& value);
  #endif
  void set_s(const char* value);
  void set_s(const char* value, size_t size);
  ::std::string* mutable_s();
  ::std::string* release_s();
  void set_allocated_s(::std::string* s);

  // string register_time = 8;
  void clear_register_time();
  static const int kRegisterTimeFieldNumber = 8;
  const ::std::string& register_time() const;
  void set_register_time(const ::std::string& value);
  #if LANG_CXX11
  void set_register_time(::std::string&& value);
  #endif
  void set_register_time(const char* value);
  void set_register_time(const char* value, size_t size);
  ::std::string* mutable_register_time();
  ::std::string* release_register_time();
  void set_allocated_register_time(::std::string* register_time);

  // string last_ip = 9;
  void clear_last_ip();
  static const int kLastIpFieldNumber = 9;
  const ::std::string& last_ip() const;
  void set_last_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_last_ip(::std::string&& value);
  #endif
  void set_last_ip(const char* value);
  void set_last_ip(const char* value, size_t size);
  ::std::string* mutable_last_ip();
  ::std::string* release_last_ip();
  void set_allocated_last_ip(::std::string* last_ip);

  // string last_login_time = 10;
  void clear_last_login_time();
  static const int kLastLoginTimeFieldNumber = 10;
  const ::std::string& last_login_time() const;
  void set_last_login_time(const ::std::string& value);
  #if LANG_CXX11
  void set_last_login_time(::std::string&& value);
  #endif
  void set_last_login_time(const char* value);
  void set_last_login_time(const char* value, size_t size);
  ::std::string* mutable_last_login_time();
  ::std::string* release_last_login_time();
  void set_allocated_last_login_time(::std::string* last_login_time);

  // string os = 11;
  void clear_os();
  static const int kOsFieldNumber = 11;
  const ::std::string& os() const;
  void set_os(const ::std::string& value);
  #if LANG_CXX11
  void set_os(::std::string&& value);
  #endif
  void set_os(const char* value);
  void set_os(const char* value, size_t size);
  ::std::string* mutable_os();
  ::std::string* release_os();
  void set_allocated_os(::std::string* os);

  // bool is_banned = 12;
  void clear_is_banned();
  static const int kIsBannedFieldNumber = 12;
  bool is_banned() const;
  void set_is_banned(bool value);

  // @@protoc_insertion_point(class_scope:DBAccount.UserAccount)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr password_hash_;
  ::google::protobuf::internal::ArenaStringPtr session_key_;
  ::google::protobuf::internal::ArenaStringPtr v_;
  ::google::protobuf::internal::ArenaStringPtr s_;
  ::google::protobuf::internal::ArenaStringPtr register_time_;
  ::google::protobuf::internal::ArenaStringPtr last_ip_;
  ::google::protobuf::internal::ArenaStringPtr last_login_time_;
  ::google::protobuf::internal::ArenaStringPtr os_;
  bool is_banned_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_game_5fdb_5faccount_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserAccount

// string user_id = 1;
inline void UserAccount::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::user_id() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.user_id)
  return user_id_.GetNoArena();
}
inline void UserAccount::set_user_id(const ::std::string& value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.user_id)
}
#if LANG_CXX11
inline void UserAccount::set_user_id(::std::string&& value) {
  
  user_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.user_id)
}
#endif
inline void UserAccount::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.user_id)
}
inline void UserAccount::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.user_id)
}
inline ::std::string* UserAccount::mutable_user_id() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_user_id() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.user_id)
  
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.user_id)
}

// string account_name = 2;
inline void UserAccount::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::account_name() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.account_name)
  return account_name_.GetNoArena();
}
inline void UserAccount::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.account_name)
}
#if LANG_CXX11
inline void UserAccount::set_account_name(::std::string&& value) {
  
  account_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.account_name)
}
#endif
inline void UserAccount::set_account_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.account_name)
}
inline void UserAccount::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.account_name)
}
inline ::std::string* UserAccount::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_account_name() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.account_name)
}

// string password = 3;
inline void UserAccount::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::password() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.password)
  return password_.GetNoArena();
}
inline void UserAccount::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.password)
}
#if LANG_CXX11
inline void UserAccount::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.password)
}
#endif
inline void UserAccount::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.password)
}
inline void UserAccount::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.password)
}
inline ::std::string* UserAccount::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_password() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.password)
}

// string password_hash = 4;
inline void UserAccount::clear_password_hash() {
  password_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::password_hash() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.password_hash)
  return password_hash_.GetNoArena();
}
inline void UserAccount::set_password_hash(const ::std::string& value) {
  
  password_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.password_hash)
}
#if LANG_CXX11
inline void UserAccount::set_password_hash(::std::string&& value) {
  
  password_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.password_hash)
}
#endif
inline void UserAccount::set_password_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.password_hash)
}
inline void UserAccount::set_password_hash(const char* value, size_t size) {
  
  password_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.password_hash)
}
inline ::std::string* UserAccount::mutable_password_hash() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.password_hash)
  return password_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_password_hash() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.password_hash)
  
  return password_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_password_hash(::std::string* password_hash) {
  if (password_hash != NULL) {
    
  } else {
    
  }
  password_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password_hash);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.password_hash)
}

// string session_key = 5;
inline void UserAccount::clear_session_key() {
  session_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::session_key() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.session_key)
  return session_key_.GetNoArena();
}
inline void UserAccount::set_session_key(const ::std::string& value) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.session_key)
}
#if LANG_CXX11
inline void UserAccount::set_session_key(::std::string&& value) {
  
  session_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.session_key)
}
#endif
inline void UserAccount::set_session_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.session_key)
}
inline void UserAccount::set_session_key(const char* value, size_t size) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.session_key)
}
inline ::std::string* UserAccount::mutable_session_key() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.session_key)
  return session_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_session_key() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.session_key)
  
  return session_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_session_key(::std::string* session_key) {
  if (session_key != NULL) {
    
  } else {
    
  }
  session_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_key);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.session_key)
}

// string v = 6;
inline void UserAccount::clear_v() {
  v_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::v() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.v)
  return v_.GetNoArena();
}
inline void UserAccount::set_v(const ::std::string& value) {
  
  v_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.v)
}
#if LANG_CXX11
inline void UserAccount::set_v(::std::string&& value) {
  
  v_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.v)
}
#endif
inline void UserAccount::set_v(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  v_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.v)
}
inline void UserAccount::set_v(const char* value, size_t size) {
  
  v_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.v)
}
inline ::std::string* UserAccount::mutable_v() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.v)
  return v_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_v() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.v)
  
  return v_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_v(::std::string* v) {
  if (v != NULL) {
    
  } else {
    
  }
  v_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), v);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.v)
}

// string s = 7;
inline void UserAccount::clear_s() {
  s_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::s() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.s)
  return s_.GetNoArena();
}
inline void UserAccount::set_s(const ::std::string& value) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.s)
}
#if LANG_CXX11
inline void UserAccount::set_s(::std::string&& value) {
  
  s_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.s)
}
#endif
inline void UserAccount::set_s(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.s)
}
inline void UserAccount::set_s(const char* value, size_t size) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.s)
}
inline ::std::string* UserAccount::mutable_s() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.s)
  return s_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_s() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.s)
  
  return s_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_s(::std::string* s) {
  if (s != NULL) {
    
  } else {
    
  }
  s_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), s);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.s)
}

// string register_time = 8;
inline void UserAccount::clear_register_time() {
  register_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::register_time() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.register_time)
  return register_time_.GetNoArena();
}
inline void UserAccount::set_register_time(const ::std::string& value) {
  
  register_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.register_time)
}
#if LANG_CXX11
inline void UserAccount::set_register_time(::std::string&& value) {
  
  register_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.register_time)
}
#endif
inline void UserAccount::set_register_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  register_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.register_time)
}
inline void UserAccount::set_register_time(const char* value, size_t size) {
  
  register_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.register_time)
}
inline ::std::string* UserAccount::mutable_register_time() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.register_time)
  return register_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_register_time() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.register_time)
  
  return register_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_register_time(::std::string* register_time) {
  if (register_time != NULL) {
    
  } else {
    
  }
  register_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), register_time);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.register_time)
}

// string last_ip = 9;
inline void UserAccount::clear_last_ip() {
  last_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::last_ip() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.last_ip)
  return last_ip_.GetNoArena();
}
inline void UserAccount::set_last_ip(const ::std::string& value) {
  
  last_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.last_ip)
}
#if LANG_CXX11
inline void UserAccount::set_last_ip(::std::string&& value) {
  
  last_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.last_ip)
}
#endif
inline void UserAccount::set_last_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  last_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.last_ip)
}
inline void UserAccount::set_last_ip(const char* value, size_t size) {
  
  last_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.last_ip)
}
inline ::std::string* UserAccount::mutable_last_ip() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.last_ip)
  return last_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_last_ip() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.last_ip)
  
  return last_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_last_ip(::std::string* last_ip) {
  if (last_ip != NULL) {
    
  } else {
    
  }
  last_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), last_ip);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.last_ip)
}

// string last_login_time = 10;
inline void UserAccount::clear_last_login_time() {
  last_login_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::last_login_time() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.last_login_time)
  return last_login_time_.GetNoArena();
}
inline void UserAccount::set_last_login_time(const ::std::string& value) {
  
  last_login_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.last_login_time)
}
#if LANG_CXX11
inline void UserAccount::set_last_login_time(::std::string&& value) {
  
  last_login_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.last_login_time)
}
#endif
inline void UserAccount::set_last_login_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  last_login_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.last_login_time)
}
inline void UserAccount::set_last_login_time(const char* value, size_t size) {
  
  last_login_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.last_login_time)
}
inline ::std::string* UserAccount::mutable_last_login_time() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.last_login_time)
  return last_login_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_last_login_time() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.last_login_time)
  
  return last_login_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_last_login_time(::std::string* last_login_time) {
  if (last_login_time != NULL) {
    
  } else {
    
  }
  last_login_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), last_login_time);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.last_login_time)
}

// string os = 11;
inline void UserAccount::clear_os() {
  os_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAccount::os() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.os)
  return os_.GetNoArena();
}
inline void UserAccount::set_os(const ::std::string& value) {
  
  os_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.os)
}
#if LANG_CXX11
inline void UserAccount::set_os(::std::string&& value) {
  
  os_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DBAccount.UserAccount.os)
}
#endif
inline void UserAccount::set_os(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  os_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DBAccount.UserAccount.os)
}
inline void UserAccount::set_os(const char* value, size_t size) {
  
  os_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DBAccount.UserAccount.os)
}
inline ::std::string* UserAccount::mutable_os() {
  
  // @@protoc_insertion_point(field_mutable:DBAccount.UserAccount.os)
  return os_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAccount::release_os() {
  // @@protoc_insertion_point(field_release:DBAccount.UserAccount.os)
  
  return os_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAccount::set_allocated_os(::std::string* os) {
  if (os != NULL) {
    
  } else {
    
  }
  os_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), os);
  // @@protoc_insertion_point(field_set_allocated:DBAccount.UserAccount.os)
}

// bool is_banned = 12;
inline void UserAccount::clear_is_banned() {
  is_banned_ = false;
}
inline bool UserAccount::is_banned() const {
  // @@protoc_insertion_point(field_get:DBAccount.UserAccount.is_banned)
  return is_banned_;
}
inline void UserAccount::set_is_banned(bool value) {
  
  is_banned_ = value;
  // @@protoc_insertion_point(field_set:DBAccount.UserAccount.is_banned)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace DBAccount

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_game_5fdb_5faccount_2eproto
