// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
class TestProto;
class TestProtoDefaultTypeInternal;
extern TestProtoDefaultTypeInternal _TestProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::TestProto* Arena::CreateMaybeMessage<::TestProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class TestProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TestProto) */ {
 public:
  TestProto();
  virtual ~TestProto();

  TestProto(const TestProto& from);

  inline TestProto& operator=(const TestProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestProto(TestProto&& from) noexcept
    : TestProto() {
    *this = ::std::move(from);
  }

  inline TestProto& operator=(TestProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestProto* internal_default_instance() {
    return reinterpret_cast<const TestProto*>(
               &_TestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TestProto* other);
  friend void swap(TestProto& a, TestProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestProto* New() const final {
    return CreateMaybeMessage<TestProto>(NULL);
  }

  TestProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestProto& from);
  void MergeFrom(const TestProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string test2 = 2;
  void clear_test2();
  static const int kTest2FieldNumber = 2;
  const ::std::string& test2() const;
  void set_test2(const ::std::string& value);
  #if LANG_CXX11
  void set_test2(::std::string&& value);
  #endif
  void set_test2(const char* value);
  void set_test2(const char* value, size_t size);
  ::std::string* mutable_test2();
  ::std::string* release_test2();
  void set_allocated_test2(::std::string* test2);

  // int32 test1 = 1;
  void clear_test1();
  static const int kTest1FieldNumber = 1;
  ::google::protobuf::int32 test1() const;
  void set_test1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr test2_;
  ::google::protobuf::int32 test1_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestProto

// int32 test1 = 1;
inline void TestProto::clear_test1() {
  test1_ = 0;
}
inline ::google::protobuf::int32 TestProto::test1() const {
  // @@protoc_insertion_point(field_get:TestProto.test1)
  return test1_;
}
inline void TestProto::set_test1(::google::protobuf::int32 value) {
  
  test1_ = value;
  // @@protoc_insertion_point(field_set:TestProto.test1)
}

// string test2 = 2;
inline void TestProto::clear_test2() {
  test2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TestProto::test2() const {
  // @@protoc_insertion_point(field_get:TestProto.test2)
  return test2_.GetNoArena();
}
inline void TestProto::set_test2(const ::std::string& value) {
  
  test2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TestProto.test2)
}
#if LANG_CXX11
inline void TestProto::set_test2(::std::string&& value) {
  
  test2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TestProto.test2)
}
#endif
inline void TestProto::set_test2(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  test2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TestProto.test2)
}
inline void TestProto::set_test2(const char* value, size_t size) {
  
  test2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TestProto.test2)
}
inline ::std::string* TestProto::mutable_test2() {
  
  // @@protoc_insertion_point(field_mutable:TestProto.test2)
  return test2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestProto::release_test2() {
  // @@protoc_insertion_point(field_release:TestProto.test2)
  
  return test2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestProto::set_allocated_test2(::std::string* test2) {
  if (test2 != NULL) {
    
  } else {
    
  }
  test2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), test2);
  // @@protoc_insertion_point(field_set_allocated:TestProto.test2)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
